FROM node:22-alpine

RUN apk add --no-cache wget libc6-compat

WORKDIR /app

COPY package.json package-lock.json ./

COPY frontend/package.json ./frontend/package.json

RUN npm ci

COPY frontend/ ./frontend/

WORKDIR /app/frontend

RUN npm run build

RUN cp -r public .next/standalone/frontend/public
RUN cp -r .next/static .next/standalone/frontend/.next/static

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nextjs -u 1001 -G nodejs
    
RUN chown -R nextjs:nodejs .next

ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"
USER nextjs

EXPOSE 3000

CMD ["node", ".next/standalone/frontend/server.js"]